framework:
    workflows:
        main:
            type: 'state_machine'
            audit_trail:
                enabled: true
            supports:
                - \App\WorkflowSubject\MainWorkflowSubject
            marking_store:
                type: 'method'
                property: 'currentPlace'
            initial_marking: 'inited'
            places:
                - start
                - inited
                - fetched
                - stored
                - end
            transitions:
                init:
                    from: start
                    to: inited
                fetching:
                    from: inited
                    to: fetched
                storing:
                    from: fetched
                    to: stored
                ending:
                    from: stored
                    to: end
                reinit:
                    from: [inited, fetched, stored, end]
                    to: inited
