framework:
    workflows:
        main:
            type: 'state_machine'
            audit_trail:
                enabled: true
            supports:
                - \App\WorkflowSubject\MainWorkflowSubject
            marking_store:
                type: 'method'
                property: 'currentPlace'
            initial_marking: start
            places:
                - start
                - inited
                - fetched
                - stored
                - end
            transitions:
                init:
                    from: start
                    to: inited
                fetching:
                    from: inited
                    to: fetched
                storing:
                    from: fetched
                    to: stored
                ending:
                    from: stored
                    to: end
            metadata:
                data_map:
                    App\Entity\JsonDataEntity:
                        author: 'json["authors"][0]["email"]'
                        project: 'json["name"]'
                        path: 'json["autoload"]["psr-4"]["App\\"]'
